import Link from 'next/link';
import type { ReactNode } from 'react';

import { env } from '@/lib/env';

/**
 * The dashboard is never statically prerendered.
 *
 * Every page here reads runtime configuration and tenant data. Prerendering would
 * evaluate env() at BUILD time, where NODE_ENV is production and the production
 * guards (mock mode rejected, ENCRYPTION_KEY required) correctly fire — failing the
 * build for a page that was always going to be rendered per-request anyway.
 */
export const dynamic = 'force-dynamic';

const NAV = [
  { href: '/dashboard', label: 'Overview' },
  { href: '/dashboard/search', label: 'Search' },
  { href: '/dashboard/leads', label: 'Leads' },
  { href: '/dashboard/jobs', label: 'Jobs' },
  { href: '/dashboard/usage', label: 'Cost' },
  { href: '/dashboard/settings', label: 'Settings' },
];

export default function DashboardLayout({ children }: { children: ReactNode }) {
  // Read on the server; this layout is a server component so no secret crosses
  // the boundary — only the boolean.
  const mockMode = env().isMockMode;

  return (
    <div className="min-h-screen">
      <header className="border-b border-[var(--border)] bg-[var(--surface)]">
        <div className="mx-auto flex max-w-7xl flex-wrap items-center gap-x-6 gap-y-2 px-4 py-3">
          <Link href="/dashboard" className="text-sm font-bold tracking-tight">
            Lead<span className="text-[var(--accent)]">Radar</span>
          </Link>

          <nav className="flex flex-wrap gap-x-4 gap-y-1 text-sm">
            {NAV.map((item) => (
              <Link
                key={item.href}
                href={item.href}
                className="text-[var(--muted)] transition-colors hover:text-[var(--foreground)]"
              >
                {item.label}
              </Link>
            ))}
          </nav>

          {/*
            Mock mode must be unmissable. A user who mistakes fabricated fixtures
            for real leads and calls them is the worst outcome this product can
            produce, so the banner is persistent rather than dismissible.
          */}
          {mockMode && (
            <span
              className="ml-auto rounded-md border border-[var(--grade-c)] px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wide text-[var(--grade-c)]"
              title="MOCK_EXTERNAL_APIS=true — all business data is fabricated sample data."
            >
              Mock data
            </span>
          )}
        </div>
      </header>

      <main className="mx-auto max-w-7xl px-4 py-6">{children}</main>

      <footer className="mx-auto max-w-7xl px-4 py-6 text-[11px] text-[var(--muted)]">
        {/* Attribution is required wherever Places data is displayed. */}
        Business listing data powered by Google. Website and social data gathered independently by
        LeadRadar. Scores and recommendations are generated by LeadRadar.
      </footer>
    </div>
  );
}
